### ISSUE TITLE
Missing synthitic_newaccount_data_50k.csv

### ISSUE THREAD

**Issue by marcotchou** [aws-samples/aws-fraud-detector-samples#2]
Hi,

I appreciate your sample code and I would like to try it but I can't find the data file - synthitic_newaccount_data_50k.csv.   Could you please let me know where to download it?   Thanks.

Regards,

Marco
mchou@cdm.depaul.edu

**Comment by zhengli0817** [comment]
Hi,

Sorry for my late reply, you can find synthetic datasets here: https://github.com/mikames/data-and-notebooks
