### ISSUE TITLE
create variable can't use the data source as 'MODEL_SCORE'

### ISSUE THREAD

**Issue by imyoungyang** [aws-samples/aws-fraud-detector-samples#3]
in the boto3 document, the dataSource can be 'MODEL_SCORE'
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/frauddetector.html#FraudDetector.Client.create_variable

But, your notebook will be failed with the following message:

ValidationException: An error occurred (ValidationException) when calling the CreateVariable operation: 1 validation error detected: Value 'MODEL_SCORE' at 'source' failed to satisfy constraint: Member must satisfy enum value set: [EXTERNAL_MODEL_SCORE, EVENT]

boto3 version is 1.16.10

**Comment by imyoungyang** [comment]
This part should be marked in your end-to-end notebook. When you create model training job, the model score variable will be created by service automatically.

#     # -- create a model score feature  
#     model_feature = "{0}_insightscore".format(MODEL_NAME)  
#     # variable_list.append( {'name' : model_feature})
#     try:
#         resp = client.get_variables(name=model_feature)
#     except:
#         print("Creating variable: {0}".format(model_feature))
#         resp = client.create_variable(
#                 name = model_feature,
#                 dataType = 'FLOAT',
#                 dataSource ='MODEL_SCORE',
#                 defaultValue = '0.0', 
#                 description = model_feature,
#                 variableType = 'NUMERIC' )

**Comment by zhengli0817** [comment]
Sorry for my late reply...

Good callout, you are right that the model score variable will be automatically created by the service, so I commented that part out in the updated end-to-end notebook
