### ISSUE TITLE
timestamp is compliant with ISO 8601 format

### ISSUE THREAD

**Issue by imyoungyang** [aws-samples/aws-fraud-detector-samples#4]
error message: ValidationException: An error occurred (ValidationException) when calling the GetEventPrediction operation: Event Timestamp is not valid. Please verify that event timestamp is compliant with ISO 8601 format.

When call function "get_event_prediction"

My code is

```
timestampStr=datetime.utcnow().replace(microsecond=0).isoformat()
```
timestampStr is like this string '2020-11-04T09:39:29'

**Comment by imyoungyang** [comment]
Got it.. need to have a "Z" in the end.
2020-11-04T09:39:29Z

**Comment by zhengli0817** [comment]
Sorry for my late replay, yes if you are using ISO 8601 standard, it needs to be in that specific format. It is documented in AFD's user guide: https://docs.aws.amazon.com/frauddetector/latest/ug/online-fraud-insights.html#preparing-training-data
